# Generated by Django 3.2.5 on 2021-07-08 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_cliente',
            fields=[
                ('id_tipo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('codigo', models.CharField(max_length=45)),
                ('fotografia', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('fk_tipo_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipo_cliente')),
            ],
        ),
    ]
