# Generated by Django 3.2.5 on 2021-07-09 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_articulo_centro_distribucion_empresa_asociada_proveedor_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_gen_pedido', models.DateField()),
                ('hora_gen_pedido', models.CharField(max_length=45)),
                ('fecha_surte_pedido', models.DateField(null=True)),
                ('hora_surte_pedido', models.CharField(max_length=45, null=True)),
                ('es_urgente', models.BooleanField()),
                ('fk_centro_distribucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.centro_distribucion')),
                ('fk_empresa_asociada', models.ManyToManyField(blank=True, to='core.Empresa_asociada')),
                ('fk_sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_pedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fk_articulo', models.ManyToManyField(blank=True, to='core.Articulo')),
                ('fk_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('fk_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pedido')),
                ('fk_proveedor', models.ManyToManyField(blank=True, to='core.Proveedor')),
            ],
        ),
    ]
