# Generated by Django 3.2.5 on 2021-07-11 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detalle_pedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fk_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente'),
        ),
    ]
